# IPs: edit ../vars.env then run external-router/frr/render-config.sh
# Generated values must match this file and ../2-frr.yaml
apiVersion: k8s.ovn.org/v1
kind: VTEP
metadata:
  name: evpn-vtep
spec:
  cidrs:
    - 192.168.61.0/24
  mode: Unmanaged
