# IPs: see ../vars.env (BASTION_IP, BGP_ASN)
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: underlay-peering
  namespace: openshift-frr-k8s
  labels:
    evpn: "true"
spec:
  nodeSelector: {}
  bgp:
    routers:
    - asn: 64513
      neighbors:
      - address: 192.168.61.10
        asn: 64513
        disableMP: true
        dualStackAddressFamily: false
        toAdvertise:
          allowed:
            mode: all
        toReceive:
          allowed:
            mode: all
