apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: advertise-evpn
spec:
  targetVRF: finance
  advertisements:
  - "PodNetwork"
  nodeSelector: {}
  frrConfigurationSelector:
    matchLabels:
      evpn: "true"
  networkSelectors:
  - networkSelectionType: ClusterUserDefinedNetworks
    clusterUserDefinedNetworkSelector:
      networkSelector:
        matchLabels:
          advertise: "true"
