hostname external-router
log stdout
log file /var/log/frr/frr.log
frr defaults traditional
!

router bgp 64513
 bgp router-id 172.19.0.1
 #no bgp default ipv4-unicast

 neighbor 172.19.0.100 remote-as 64513
 neighbor 172.19.0.101 remote-as 64513
 neighbor 172.19.0.102 remote-as 64513

 address-family ipv4 unicast
  neighbor 172.19.0.100 activate
  neighbor 172.19.0.100 next-hop-self
  neighbor 172.19.0.101 activate
  neighbor 172.19.0.101 next-hop-self
  neighbor 172.19.0.102 activate
  neighbor 172.19.0.102 next-hop-self
  redistribute connected
  redistribute static
 exit-address-family

 address-family l2vpn evpn
  neighbor 172.19.0.100 activate
  neighbor 172.19.0.101 activate
  neighbor 172.19.0.102 activate
  advertise-all-vni
  advertise-svi-ip
  advertise-gateway-macip
  vni 100
 exit-address-family
!
