hostname bgpd-external
log stdout debugging
log file /var/log/frr/frr.log debugging
log timestamp precision 3
frr defaults traditional
!
! Global Debugging Settings
debug bgp updates
debug bgp events
debug bgp evpn
debug bgp nht detail
debug zebra vxlan
debug zebra kernel
!
! === Underlay + EVPN (all in default VRF) ===
router bgp 64513
 bgp router-id 172.19.0.1 
 no bgp default ipv4-unicast

 neighbor 172.19.0.100 remote-as 64513
 neighbor 172.19.0.101 remote-as 64513
 neighbor 172.19.0.102 remote-as 64513

 neighbor 172.19.0.100 allowas-in origin
 neighbor 172.19.0.101 allowas-in origin
 neighbor 172.19.0.102 allowas-in origin

 address-family ipv4 unicast
  neighbor 172.19.0.100 activate
  neighbor 172.19.0.100 next-hop-self
  neighbor 172.19.0.101 activate
  neighbor 172.19.0.101 next-hop-self
  neighbor 172.19.0.102 activate
  neighbor 172.19.0.102 next-hop-self
  network 100.64.0.1/32
  redistribute static
  redistribute connected
 exit-address-family

 address-family l2vpn evpn
  neighbor 172.19.0.100 activate
  neighbor 172.19.0.101 activate
  neighbor 172.19.0.102 activate
  advertise-all-vni
  advertise-svi-ip
  advertise-gateway-macip
 exit-address-family
!
end