apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: node-2-fixed-ip
spec:
  nodeSelector: 
    node: "2"
  desiredState:
    interfaces:
    - name: enp3s0  # Explicitly disable IP on the physical NIC
      type: ethernet
      state: up
      ipv4:
        dhcp: false
        address:
          - ip: 172.19.0.101
            prefix-length: 24
        enabled: true 
      ipv6:
        enabled: false
        
