hostname bgpd-external
log stdout debugging
log file /var/log/frr/frr.log debugging
log timestamp precision 3
frr defaults traditional
!
debug bgp updates
debug bgp events
debug bgp evpn
debug bgp nht detail
debug zebra vxlan
debug zebra kernel
!
interface vni100
 evpn vni 100
!
router bgp 64513
 bgp router-id 192.168.61.10
 no bgp default ipv4-unicast

 neighbor 192.168.61.41 remote-as 64513
 neighbor 192.168.61.73 remote-as 64513

 neighbor 192.168.61.41 allowas-in origin
 neighbor 192.168.61.73 allowas-in origin

 address-family ipv4 unicast
  neighbor 192.168.61.41 activate
  neighbor 192.168.61.41 next-hop-self
  neighbor 192.168.61.73 activate
  neighbor 192.168.61.73 next-hop-self
  redistribute static
  redistribute connected
 exit-address-family

 address-family l2vpn evpn
  neighbor 192.168.61.41 activate
  neighbor 192.168.61.73 activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
!
end
